name: Baselines

on:
  workflow_dispatch:
  schedule:
    - cron: '43 13 * * 0' # runs only on Sundays
  
jobs:
  baselines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: submit
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: './examples'

    - name: Run baseline models
      run: Rscript examples/baselines.R

    - name: Commit & push changes
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git add submissions/*
        git commit -m 'add new baseline submissions'
        git push
