# This is a basic workflow to help you get started with Actions

name: Scheduled eval trigger

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '39 8 * * *' # every morning

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  trigger:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Evaluation triggered on schedule"
